### ISSUE TITLE
fix: reportWebVitals.ts 

### ISSUE THREAD

**Issue by hoseong511** [4transcendence2/frontend#19]
필요한건가요?
https://github.com/4transcendence2/frontend/blob/71a47287411c5d01234d66bee7f5b640cd13ddac/src/reportWebVitals.ts#L1-L15

**Comment by sumnii** [comment]
아 이거 cra로 처음 만들었을 때 생긴건데, vite로 마이그레이션 하고 그대로 있었던 것 같아요~! 아까 저도 작업하면서 삭제해서 지금 PR 올린 브랜치 머지하면 사라집니다!
