### ISSUE TITLE
fix: 여러 탭을 실행 중 로그아웃 후 로그인 화면 x

### ISSUE THREAD

**Issue by hoseong511** [4transcendence2/frontend#37]
## Desc
여러 탭 실행 중 로그아웃 후 로그인 화면으로 이동하지 않는 현상

## Detail
1. 같은 계정으로 여러 탭에서 실행 중
2. 최초 로그인한 탭이 아닌 탭에서 로그아웃 시도
3. `Uncaught TypeError: Cannot read properties of undefined (reading 'disconnect')` 에러 발생
4. 이 후 새로고침 하면 로그인 화면

## Todo
- [x] 로그아웃 후 로그인 화면 이동 x

**Comment by hoseong511** [comment]
https://github.com/4transcendence2/frontend/blob/60d1671f2be8b0e76c584164a1d35473611771b5/src/socket/socket.ts#L23-L26

해당 부분에서 socket이 있는 경우 disconnect 처리
```ts
export function disconnectSocket() { 
  if (socket) {
   socket.disconnect(); 
   console.log("disconnect", socket); 
   }
 } 
```
### comment
이전 작업 브랜치들이 순서대로 머지가 되면 수정할게요!

**Comment by hoseong511** [comment]
++ 소켓 관련
최초 탭에 로그인한 후 다른 탭에서 접속 했을 시 소켓을 어떻게 처리할지

**Comment by sumnii** [comment]
> ++ 소켓 관련 최초 탭에 로그인한 후 다른 탭에서 접속 했을 시 소켓을 어떻게 처리할지

요건 기억하려고 적어두신걸까요!
